### ISSUE TITLE
KeyError: 'run_id'

### ISSUE THREAD

**Issue by 0x366** [drivendataorg/power-laws-optimization#2]
Hello, I'm getting this traceback when running `run.sh` :
```
Successfully built 94200d9658eb
Successfully tagged power-laws-optimization/simulate:latest
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
sites                   : 100%|██████████| 187/187 [00:00<00:00, 10495.72it/s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'run_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simulate/simulate.py", line 195, in <module>
    results_df = pd.DataFrame(results).set_index('run_id')
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py", line 3146, in set_index
    level = frame[col]._values
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'run_id'
ERROR: Script did execute correctly or timed out.
```

**Comment by pjbull** [comment]
Did you follow the instructions on the README and place the downloaded `metadata.csv` into the `data` folder?
https://github.com/drivendataorg/power-laws-optimization#running-the-simulation

**Comment by 0x366** [comment]
Sorry, I'm really bad - I used the data from another "Power Law" competition. :sweat_smile: 

Thank you!
